# Generated by Django 4.0.3 on 2022-04-01 15:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_fate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 1, 15, 30, 13, 568582, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 1, 15, 30, 13, 567582, tzinfo=utc)),
        ),
    ]
